const testIds = {
	/*eslint sort-keys: ["error", "asc"]*/
	BUTTON_ROW: "mos:ButtonRow:row",
	BUTTON_SKELETON: "mos:ButtonRow:skeleton",
	CARD: "mos:Card:root",
	CARD_HEADING: "mos:Card:heading",
	CARD_ITEM: "mos:Card:item",
	CARD_TITLE_ICON: "mos:Card:titleIcon",
	CHECKBOX_WRAPPER: "mos:Checkbox:wrapper",
	CHIP_DELETE_ICON: "mos:Chip:deleteIcon",
	CONTENT: "mos:Content:root",
	CONTENT_COL: "mos:Content:col",
	CONTENT_FIELD: "mos:Content:field",
	CONTENT_ROW: "mos:Content:row",
	CONTENT_SECTION: "mos:Content:section",
	CONTENT_TOOLTIP_ICON: "mos:Content:tooltipIcon",
	DATA_VIEW_ACTIONS_ROW: "mos:DataView:actionsRow",
	DATA_VIEW_BULK_ALL: "mos:DataView:bulkAll",
	DATA_VIEW_CELL_CHECK: "mos:DataView:cellCheck",
	DATA_VIEW_CELL_DRAG: "mos:DataView:cellDrag",
	DATA_VIEW_DISPLAY_CONTROL: "mos:DataView:displayControl",
	DATA_VIEW_DISPLAY_GRID: "mos:DataView:displayGrid",
	DATA_VIEW_DISPLAY_LIST: "mos:DataView:displayList",
	DATA_VIEW_FILTERS: "mos:DataView:filters",
	DATA_VIEW_FILTER_BAR: "mos:DataView:filterBar",
	DATA_VIEW_FILTER_MULTI_COUNTER: "mos:DataView:filterMultiCounter",
	DATA_VIEW_GRID_ITEM: "mos:DataView:gridItem",
	DATA_VIEW_GRID_ITEM_CHECK: "mos:DataView:gridItemCheck",
	DATA_VIEW_LIMIT_CONTROL: "mos:DataView:limitControl",
	DATA_VIEW_PAGER: "mos:DataView:pager",
	DATA_VIEW_SORT_ASC: "mos:DataView:sortAsc",
	DATA_VIEW_SORT_DESC: "mos:DataView:sortDesc",
	DATA_VIEW_TBODY: "mos:DataView:tableBody",
	DATA_VIEW_TITLE_BAR: "mos:DataView:titleBar",
	DATA_VIEW_VIEW_APPLY: "mos:DataView:view:apply",
	DATA_VIEW_VIEW_CONTROL: "mos:DataView:viewControl",
	DATA_VIEW_VIEW_DELETE: "mos:DataView:view:delete",
	FORM_FIELD_LABEL: "mos:Field:label",
	FORM_STATE: "mos:Form:state",
	TEXT_EDITOR_CANVAS: "mos:TextEditor:canvas",
	TEXT_EDITOR_CODE: "mos:TextEditor:code",
	TEXT_EDITOR_CONTROL: "mos:TextEditor:control",
	TEXT_EDITOR_FLOATING_TOOLBAR: "mos:TextEditor:floatingToolbar",
	TEXT_EDITOR_HEADING_CONTROL: "mos:TextEditor:headingControl",
	TEXT_EDITOR_HEADING_MENU: "mos:TextEditor:headingMenu",
	TEXT_EDITOR_PRIMARY_TOOLBAR: "mos:TextEditor:primaryToolbar",
	TOGGLE: "mos:Toggle:root",
	TOP_SUMMARY: "mos:TopSummary:root",
} as const;

export default testIds;
