services:
  mosaic:
    image: mosaic:local
    container_name: mosaic
    build: ./containers/mosaic
    volumes:
      - mosaic:/app
      - /app/.yarn/
      - /app/node_modules/
  mosaic-units:
    container_name: mosaic-units
    extends: mosaic
    environment:
      - CI=true
    command: ["yarn", "test"]
  mosaic-dev:
    container_name: mosaic-dev
    extends: mosaic
    volumes:
      - ./containers/mosaic/src:/app/src
    command: ["yarn", "start"]
  mosaic-publish:
    container_name: mosaic-publish
    extends: mosaic
    environment:
      - CIRCLE_BRANCH=${CIRCLE_BRANCH}
      - CIRCLE_SHA1=${CIRCLE_SHA1}
      - NPM_TOKEN=${NPM_TOKEN}
    command: ["yarn", "publish:npm"]
  # mosaic-types:
  #   image: mosaic-types:local
  #   container_name: mosaic-types
  #   build: ./containers/mosaic-types
  #   volumes:
  #     - sv-mosaic-types:/app
  #   depends_on:
  #     - mosaic
  storybook:
    build: ./containers/sb-8
    volumes:
      - mosaic:/mosaic
      - storybook-static:/app/storybook-static
    depends_on:
      - mosaic
    ports:
      - 10001:10001
  storybook-dev:
    container_name: storybook-dev
    extends: storybook
    volumes:
      - ./containers/sb-8/stories:/app/stories
    depends_on:
      - mosaic-dev
    command: ["yarn", "start"]

  storybook-serve:
    container_name: storybook-serve
    extends: storybook
    command: bash -c "npx --yes http-server ./storybook-static -p 10001 --silent"
  e2e-tests:
    container_name: e2e-tests
    build: ./containers/e2e-tests
    volumes:
      - mosaic:/mosaic
    command: npm start
  consumer-tests:
    container_name: consumer-tests
    build: ./containers/consumer-tests
    volumes:
      - mosaic:/mosaic
    depends_on:
      - mosaic
    command: npm start
  storybook-publish:
    container_name: storybook-publish
    extends: storybook
    environment:
      - CIRCLE_BRANCH=${CIRCLE_BRANCH}
    volumes:
      - /home/circleci/.ssh:/root/.ssh
    command: yarn publish:init
volumes:
  mosaic:
  storybook-static:
