#!/bin/bash
docker run --rm -it \
	-v $PWD/src:/app/src \
	-v $PWD/.storybook:/app/.storybook \
	-v $PWD/dist:/app/dist \
	-v $PWD/package.json:/app/mounted/package.json \
	-v $PWD/yarn.lock:/app/mounted/yarn.lock \
	-v $PWD/.yarn:/app/mounted/.yarn \
	-v $PWD/webpack.config.js:/app/webpack.config.js \
	-v $PWD/.babelrc:/app/.babelrc \
	-v $PWD/tsconfig.json:/app/tsconfig.json \
	-v $PWD/.eslintrc.json:/app/.eslintrc.json \
	-v $PWD/.eslintignore:/app/.eslintignore \
	-p 10000:10000 \
	sv-mosaic:local /bin/bash
