#!/bin/bash
# NOTE: Don't run this script with PRs, wait until it's merged to develop, this prevents complicated merge conflicts between pending PRS
bash ./scripts/build

docker create --name sv-mosaic sv-mosaic:local /bin/sh

docker cp sv-mosaic:/app/package.json ./package.json
docker cp sv-mosaic:/app/yarn.lock ./yarn.lock
rm -rf ./.yarn/*
docker cp sv-mosaic:/app/.yarn/. ./.yarn
docker rm -fv sv-mosaic
echo "complete"