#!/bin/bash
docker run --rm -it \
	-v $PWD/src:/app/src \
	-v $PWD/dist:/app/dist \
	-v $PWD/testing:/app/testing \
	-v $PWD/package.json:/app/package.json \
	-v $PWD/webpack.config.js:/app/webpack.config.js \
	-v $PWD/.babelrc:/app/.babelrc \
	-p 10000:10000 \
	sv-mosaic:local /bin/bash