#!/bin/bash
docker run --rm -it \
	-v $PWD/src:/app/src \
	-v $PWD/../storybook-5/src:/app/lib/src \
	-v sv-mosaic-modules:/app/lib/node_modules \
	-p 10001:10001 \
	-e NODE_OPTIONS=--openssl-legacy-provider \
	sv-mosaic-sb7 \
	bash
