import { test, expect } from "@playwright/test";
import { FormFieldAddressPage } from "../../pages/FormFields/FormFieldAddressPage";
import { randomIntFromInterval } from "../../utils/helpers/helper";

test.describe("FormFields - FormFieldAddress - Kitchen Sink", () => {
	let ffAddressPage: FormFieldAddressPage;

	test.beforeEach(async ({ page }) => {
		ffAddressPage = new FormFieldAddressPage(page);
		await ffAddressPage.visitPage();
	});

	test("Validate that Postal Code type is equal to String.", async () => {
		await ffAddressPage.addAddressButton.click();
		expect(await ffAddressPage.postalCodeField.getAttribute("type")).toBe("string");
	});

	test("Validate the Postal Code field.", async () => {
		await ffAddressPage.addAddressButton.click();
		const randomNumber = randomIntFromInterval(0, 99999999);
		const randomString = await ffAddressPage.getAutogeneratedText(20);

		await ffAddressPage.postalCodeField.type(randomNumber.toString());
		expect(Number(await ffAddressPage.postalCodeField.inputValue())).toBe(randomNumber);

		await ffAddressPage.postalCodeField.selectText();
		await ffAddressPage.clearAllValuesFromField();		
		await ffAddressPage.postalCodeField.type(randomString);
		expect(await ffAddressPage.postalCodeField.inputValue()).toBe(randomString);
	});
});