import { Locator, Page } from "@playwright/test";
import { BasePage } from "../BasePage";
import { generateRandomId } from "../../utils/helpers/helper";

export class FormFieldBasePage extends BasePage {
	
	readonly page: Page;

	constructor(page: Page) {
		super(page);
		this.page = page;
	}
	
	async getAutogeneratedText(length: number): Promise<string> {
		return generateRandomId(length);
	}

	async getLimitOfMaxChar(locator: Locator): Promise<number> {
		const textContent = await locator.textContent();
		return Number(textContent?.split("/")[1]);
	}
	
	async getNumberOfCharactersInMaxCharField(locator: Locator): Promise<number> {
		const textContent = await locator.textContent();
		return Number(textContent?.split("/")[0]);
	}
}