#!/bin/bash
# Meant to be run inside the docker container

rm -rf ./types-only
mkdir -p ./types-only
cp -a ./dist/types/. ./types-only/types

# extract package.json version
export VERSION=$(jq -r ".version" ./package.json)
# generate new package json for types
envsubst < ./src/package-types.json > ./types-only/package.json
