#!/bin/bash
git push fork

github_repo="https://github.com/simpleviewinc/sv-mosaic"
jira_issues="https://simpleviewtools.atlassian.net/browse"

branch_name=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
fork_url=$(git remote get-url fork)
fork_path=$(sed -e "s#https://github\.com/##g" <<< $fork_url)
fork=$(sed -e "s#/#:#g" <<< $fork_path)
issue_tag=$(sed -n "s/^\(MOS-[0-9]\+\).*$/\1/p" <<< $branch_name)

read -r -d '' description <<- EOM
# [${issue_tag}](${jira_issues}/${issue_tag})

## Description
- _Describe the issue..._

## Checklist
- [ ] I have written new tests to cover the changes
- [ ] I have written/updated documentation to cover the changes
- [ ] I have verified these changes in all major browsers
- [ ] This contains breaking changes
EOM

url=$(curl \
    -s \
    --get \
    -w %{url_effective} \
    --data-urlencode "quick_pull=1" \
    --data-urlencode "title=${issue_tag}" \
    --data-urlencode "body=${description}" \
    --connect-timeout 0.01 \
    "${github_repo}/compare/develop...${fork}:${branch_name}"
)

echo "${url}"
