#!/bin/bash

cd automation_testing
npm install

STORYBOOK_URL=http://storybook:10001/iframe.html
INTERVAL=30

until curl --head --silent --fail $STORYBOOK_URL 1> /dev/null 2>&1; do
    echo "Storybook is not ready. Trying again in ${INTERVAL} seconds..."
    sleep $INTERVAL
done

ENV=docker npm run test:chrome
