import { expect, Page, Locator } from "@playwright/test";
import { url } from "../utils/formUrls";
import { generateRandomId } from "../utils/helpers/helper";

export class BasePage {

	readonly page: Page;
	readonly loading: Locator;
	readonly title: Locator;
	readonly applyBtn: Locator;
	readonly clearBtn: Locator;
	readonly cancelBtn: Locator;
	readonly saveBtn: Locator;
	readonly table: Locator;
	readonly errorMessage: Locator;
	readonly latitude: Locator;
	readonly longitude: Locator;
	readonly saveCoordinatesButton: Locator;
	readonly drawerSaveButton: Locator;
	readonly drawerCancelButton: Locator;

	constructor(page: Page) {
		this.page = page;
		this.loading = page.locator("div.loading");
		this.title = page.locator("text=Form Title");
		this.applyBtn = page.locator("text=Apply");
		this.clearBtn = page.locator("text=Clear");
		this.cancelBtn = page.locator("text=Cancel");
		this.saveBtn = page.locator("text=Save");
		this.table = page.locator("table");
		this.errorMessage = page.locator("p.Mui-error");
		this.latitude = page.locator("#lat");
		this.longitude = page.locator("#lng");
		this.saveCoordinatesButton = page.locator("[type='DRAWER'] button", { hasText: "Save Coordinates"})
		this.drawerSaveButton = page.locator("[type='DRAWER'] button", { hasText: "Save" });
		this.drawerCancelButton = page.locator("[type='DRAWER'] button", { hasText: "Cancel" });
	}

	async visit(page_path: string, element: Locator): Promise<void> {
		await this.page.goto(url(page_path), { timeout: 900000 });
		await element.waitFor();
	}

	async validateSnapshot(component: Locator, name: string): Promise<void> {
		await component.waitFor({ state: "visible" });
		await component.waitFor({ state: "attached" });
		await this.loading.waitFor({ state: "detached" });
		expect(await component.screenshot()).toMatchSnapshot("dataview-" + name + ".png", { threshold: 0.3, maxDiffPixelRatio: 0.3 })
	}

	async wait(): Promise<void> {
		await this.page.waitForTimeout(500);
	}

	async waitForElementLoad(): Promise<void> {
		await this.loading.waitFor({ state: "detached" });
	}

	async clearAllValuesFromField(): Promise<void> {
		await this.page.keyboard.press("Home");
		await this.page.keyboard.down("Shift");
		await this.page.keyboard.press("End");
		await this.page.keyboard.up("Shift");
		await this.page.keyboard.press("Backspace");
	}

	async getElementWidth(element:Locator):Promise<number> {
		await element.waitFor({ state: "visible" });
		const width = (await ((element).evaluate(el => getComputedStyle(el).width))).split("px")[0];
		const leftPadding = ((await ((element).evaluate(el => getComputedStyle(el).paddingLeft))).split("px")[0]);
		const rightPadding = ((await ((element).evaluate(el => getComputedStyle(el).paddingRight))).split("px")[0]);
		return Number(width) + Number(leftPadding) + Number(rightPadding);
	}

	async getAutogeneratedText(length: number): Promise<string> {
		return generateRandomId(length);
	}

	async getLimitOfMaxChar(locator: Locator): Promise<number> {
		const textContent = await locator.textContent();
		return Number(textContent?.split("/")[1]);
	}

	async getNumberOfCharactersInMaxCharField(locator: Locator): Promise<number> {
		const textContent = await locator.textContent();
		return Number(textContent?.split("/")[0]);
	}

	async selectOptionFromDropdown(dropdown: Locator, option:string): Promise<void> {
		await dropdown.click({force: true});
		await this.page.locator("text=" + option).nth(0).click();
	}
}
